Fix for detection of truecolor gd library support (Lars Hecking)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -719,6 +719,7 @@ PATH_TO_TRACEROUTE
 PACKDIR
 VERSION
 subdirs
+USE_LIBTAP
 CGIEXTRAS
 GDLIBS
 PERLLIBS
@@ -6953,6 +6954,75 @@ echo "${ECHO_T}no" >&6; }
 _ACEOF
 
 			CGIEXTRAS="$CGIEXTRAS statusmap.cgi"
+			{ echo "$as_me:$LINENO: checking for gdImageCreateTrueColor in -lgd" >&5
+echo $ECHO_N "checking for gdImageCreateTrueColor in -lgd... $ECHO_C" >&6; }
+if test "${ac_cv_lib_gd_gdImageCreateTrueColor+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgd  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char gdImageCreateTrueColor ();
+int
+main ()
+{
+return gdImageCreateTrueColor ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_gd_gdImageCreateTrueColor=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_gd_gdImageCreateTrueColor=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_gd_gdImageCreateTrueColor" >&5
+echo "${ECHO_T}$ac_cv_lib_gd_gdImageCreateTrueColor" >&6; }
+if test $ac_cv_lib_gd_gdImageCreateTrueColor = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GDIMAGECREATETRUECOLOR 1
+_ACEOF
+
+fi
+
 		fi
 
 				cat >>confdefs.h <<_ACEOF
@@ -7909,7 +7979,11 @@ fi
 if test "$enable_libtap" = "yes" ; then
 	subdirs="$subdirs tap"
 
+	USE_LIBTAP=yes
+else
+	USE_LIBTAP=no
 fi
+
 
 
 
@@ -8686,6 +8760,7 @@ PATH_TO_TRACEROUTE!$PATH_TO_TRACEROUTE$ac_delim
 PACKDIR!$PACKDIR$ac_delim
 VERSION!$VERSION$ac_delim
 subdirs!$subdirs$ac_delim
+USE_LIBTAP!$USE_LIBTAP$ac_delim
 CGIEXTRAS!$CGIEXTRAS$ac_delim
 GDLIBS!$GDLIBS$ac_delim
 PERLLIBS!$PERLLIBS$ac_delim
@@ -8702,7 +8777,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 22; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 23; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
