add config checks for start, reload and restart on rhel init script

diff --git a/daemon-init-redhat.in b/daemon-init-redhat.in
--- a/daemon-init-redhat.in
+++ b/daemon-init-redhat.in
@@ -65,9 +65,19 @@ force_reload() {
     restart
 }
 
+check_config() {
+        $nice runuser -s /bin/bash - $user -c "$corelimit >/dev/null 2>&1 ; $exec -v $config > /dev/null 2>&1"
+	RETVAL=$?
+	if [ $RETVAL -ne 0 ] ; then
+		echo "Configuration error: please check the config by runing \"$exec -v $config\""
+		exit 1
+	fi
+}
+
 case "$1" in
     start)
         status $prog && exit 0
+	check_config
         $1
         ;;
     stop)
@@ -75,10 +85,12 @@ case "$1" in
         $1
         ;;
     restart)
+	check_config
         $1
         ;;
     reload)
         status $prog || exit 7
+	check_config
         $1
         ;;
     force-reload)
@@ -92,8 +104,7 @@ case "$1" in
         restart
         ;;
    configtest)
-        $nice runuser -s /bin/bash - $user -c "$corelimit >/dev/null 2>&1 ; $exec -v $config"
-	RETVAL=$?
+	check_config
 	;;
     *)
         echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|configtest}"
